//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_First.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class assignment
    {
        public assignment()
        {
            this.assignmentResults = new HashSet<assignmentResult>();
        }
    
        public int aid { get; set; }
        public string tid { get; set; }
        public string cid { get; set; }
        public int totalMarks { get; set; }
        public string questionFilePath { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
        public string solutionFilePath { get; set; }
        public int aNumber { get; set; }
    
        public virtual teacher teacher { get; set; }
        public virtual cours cours { get; set; }
        public virtual ICollection<assignmentResult> assignmentResults { get; set; }
    }
}
