//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_First.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class attendance
    {
        public string studentId { get; set; }
        public string courseId { get; set; }
        public int presents { get; set; }
        public int absents { get; set; }
        public string tName { get; set; }
    
        public virtual student student { get; set; }
        public virtual cours cours { get; set; }
        public virtual teacher teacher { get; set; }
    }
}
