//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_First.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public comment()
        {
            this.users = new HashSet<user>();
        }
    
        public int comID { get; set; }
        public int pid { get; set; }
        public string body { get; set; }
        public System.DateTime time { get; set; }
        public int likes { get; set; }
        public string c_creator { get; set; }
    
        public virtual user user { get; set; }
        public virtual post post { get; set; }
        public virtual ICollection<user> users { get; set; }
    }
}
