//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_First.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class group
    {
        public group()
        {
            this.posts = new HashSet<post>();
        }
    
        public int gid { get; set; }
        public string name { get; set; }
        public string g_creator { get; set; }
        public System.DateTime time { get; set; }
        public string @class { get; set; }
    
        public virtual user user { get; set; }
        public virtual ICollection<post> posts { get; set; }
    }
}
