//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_First.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogStudent
    {
        public int Id { get; set; }
        public string courseId { get; set; }
        public string tName { get; set; }
        public System.DateTime date { get; set; }
        public string type { get; set; }
        public int totalMarks { get; set; }
        public string discription { get; set; }
    }
}
