//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_First.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PucitDBEntities : DbContext
    {
        public PucitDBEntities()
            : base("name=PucitDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Announcement> Announcements { get; set; }
        public DbSet<assignment> assignments { get; set; }
        public DbSet<assignmentResult> assignmentResults { get; set; }
        public DbSet<attendance> attendances { get; set; }
        public DbSet<attendance1> attendance1 { get; set; }
        public DbSet<comment> comments { get; set; }
        public DbSet<cours> courses { get; set; }
        public DbSet<DateSheet> DateSheets { get; set; }
        public DbSet<group> groups { get; set; }
        public DbSet<Log> Logs { get; set; }
        public DbSet<LogStudent> LogStudents { get; set; }
        public DbSet<LogTeacher> LogTeachers { get; set; }
        public DbSet<post> posts { get; set; }
        public DbSet<question> questions { get; set; }
        public DbSet<quiz> quizs { get; set; }
        public DbSet<quizResult> quizResults { get; set; }
        public DbSet<semester> semesters { get; set; }
        public DbSet<student> students { get; set; }
        public DbSet<teacher> teachers { get; set; }
        public DbSet<teacherClass> teacherClasses { get; set; }
        public DbSet<user> users { get; set; }
    }
}
