//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_First.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NudbEntities : DbContext
    {
        public NudbEntities()
            : base("name=NudbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Announcement> Announcements { get; set; }
        public virtual DbSet<assignment> assignments { get; set; }
        public virtual DbSet<assignmentResult> assignmentResults { get; set; }
        public virtual DbSet<attendance> attendances { get; set; }
        public virtual DbSet<attendance1> attendance1 { get; set; }
        public virtual DbSet<comment> comments { get; set; }
        public virtual DbSet<cours> courses { get; set; }
        public virtual DbSet<FileData> FileDatas { get; set; }
        public virtual DbSet<group> groups { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<LogStudent> LogStudents { get; set; }
        public virtual DbSet<LogTeacher> LogTeachers { get; set; }
        public virtual DbSet<post> posts { get; set; }
        public virtual DbSet<question> questions { get; set; }
        public virtual DbSet<quiz> quizs { get; set; }
        public virtual DbSet<quizResult> quizResults { get; set; }
        public virtual DbSet<semester> semesters { get; set; }
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<teacher> teachers { get; set; }
        public virtual DbSet<teacherClass> teacherClasses { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
