//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_First.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class question
    {
        public int quid { get; set; }
        public string statement { get; set; }
        public string option_A { get; set; }
        public string option_B { get; set; }
        public string Option_C { get; set; }
        public string option_D { get; set; }
        public string correctOption { get; set; }
        public int marks { get; set; }
        public string solution { get; set; }
        public string cid { get; set; }
        public string topic { get; set; }
    
        public virtual cours cours { get; set; }
    }
}
