//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_First.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class quiz
    {
        public quiz()
        {
            this.quizResults = new HashSet<quizResult>();
        }
    
        public int qid { get; set; }
        public string cid { get; set; }
        public string tid { get; set; }
        public int totalQuestion { get; set; }
        public int TotalMarks { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
        public int TotalTime { get; set; }
        public string topic { get; set; }
        public Nullable<int> totalAttempts { get; set; }
        public Nullable<int> quizNum { get; set; }
    
        public virtual cours cours { get; set; }
        public virtual teacher teacher { get; set; }
        public virtual ICollection<quizResult> quizResults { get; set; }
    }
}
