//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_First.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class semester
    {
        public semester()
        {
            this.students = new HashSet<student>();
            this.courses = new HashSet<cours>();
        }
    
        public int smid { get; set; }
        public Nullable<int> credithours { get; set; }
        public Nullable<double> gpa { get; set; }
    
        public virtual ICollection<student> students { get; set; }
        public virtual ICollection<cours> courses { get; set; }
    }
}
