//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_First.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public student()
        {
            this.assignmentResults = new HashSet<assignmentResult>();
            this.attendances = new HashSet<attendance>();
            this.attendance1 = new HashSet<attendance1>();
            this.Logs = new HashSet<Log>();
            this.quizResults = new HashSet<quizResult>();
            this.courses = new HashSet<cours>();
        }
    
        public string sid { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public string degree { get; set; }
        public string session { get; set; }
        public string batch { get; set; }
        public Nullable<int> smid { get; set; }
        public Nullable<double> cgpa { get; set; }
        public string address { get; set; }
        public string section { get; set; }
        public string semester { get; set; }
    
        public virtual ICollection<assignmentResult> assignmentResults { get; set; }
        public virtual ICollection<attendance> attendances { get; set; }
        public virtual ICollection<attendance1> attendance1 { get; set; }
        public virtual ICollection<Log> Logs { get; set; }
        public virtual ICollection<quizResult> quizResults { get; set; }
        public virtual semester semester1 { get; set; }
        public virtual ICollection<cours> courses { get; set; }
    }
}
