//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_First.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.Announcements = new HashSet<Announcement>();
            this.comments = new HashSet<comment>();
            this.groups = new HashSet<group>();
            this.posts = new HashSet<post>();
            this.comments1 = new HashSet<comment>();
            this.posts1 = new HashSet<post>();
        }
    
        public string uid { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public string dept { get; set; }
    
        public virtual ICollection<Announcement> Announcements { get; set; }
        public virtual ICollection<comment> comments { get; set; }
        public virtual ICollection<group> groups { get; set; }
        public virtual ICollection<post> posts { get; set; }
        public virtual ICollection<comment> comments1 { get; set; }
        public virtual ICollection<post> posts1 { get; set; }
    }
}
